package com.aifule.jxc.core.domain;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addId
     *
     * @mbg.generated
     */
    private Integer addid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.details
     *
     * @mbg.generated
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addId
     *
     * @return the value of address.addId
     * @mbg.generated
     */
    public Integer getAddid() {
        return addid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addId
     *
     * @param addid the value for address.addId
     * @mbg.generated
     */
    public void setAddid(Integer addid) {
        this.addid = addid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.uid
     *
     * @return the value of address.uid
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.uid
     *
     * @param uid the value for address.uid
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.details
     *
     * @return the value of address.details
     * @mbg.generated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.details
     *
     * @param details the value for address.details
     * @mbg.generated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Address other = (Address) that;
        return (this.getAddid() == null ? other.getAddid() == null : this.getAddid().equals(other.getAddid()))
                && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
                && (this.getDetails() == null ? other.getDetails() == null : this.getDetails().equals(other.getDetails()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAddid() == null) ? 0 : getAddid().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getDetails() == null) ? 0 : getDetails().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", addid=").append(addid);
        sb.append(", uid=").append(uid);
        sb.append(", details=").append(details);
        sb.append("]");
        return sb.toString();
    }
}