package com.aifule.jxc.core.domain;

public class Admins {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.aid
     *
     * @mbg.generated
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.aname
     *
     * @mbg.generated
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admins.apwd
     *
     * @mbg.generated
     */
    private String apwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.aid
     *
     * @return the value of admins.aid
     * @mbg.generated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.aid
     *
     * @param aid the value for admins.aid
     * @mbg.generated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.aname
     *
     * @return the value of admins.aname
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.aname
     *
     * @param aname the value for admins.aname
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admins.apwd
     *
     * @return the value of admins.apwd
     * @mbg.generated
     */
    public String getApwd() {
        return apwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admins.apwd
     *
     * @param apwd the value for admins.apwd
     * @mbg.generated
     */
    public void setApwd(String apwd) {
        this.apwd = apwd == null ? null : apwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Admins other = (Admins) that;
        return (this.getAid() == null ? other.getAid() == null : this.getAid().equals(other.getAid()))
                && (this.getAname() == null ? other.getAname() == null : this.getAname().equals(other.getAname()))
                && (this.getApwd() == null ? other.getApwd() == null : this.getApwd().equals(other.getApwd()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAid() == null) ? 0 : getAid().hashCode());
        result = prime * result + ((getAname() == null) ? 0 : getAname().hashCode());
        result = prime * result + ((getApwd() == null) ? 0 : getApwd().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admins
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", aid=").append(aid);
        sb.append(", aname=").append(aname);
        sb.append(", apwd=").append(apwd);
        sb.append("]");
        return sb.toString();
    }
}