package com.aifule.jxc.core.domain;

public class Inventory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.inid
     *
     * @mbg.generated
     */
    private Integer inid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.gid
     *
     * @mbg.generated
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.inid
     *
     * @return the value of inventory.inid
     * @mbg.generated
     */
    public Integer getInid() {
        return inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.inid
     *
     * @param inid the value for inventory.inid
     * @mbg.generated
     */
    public void setInid(Integer inid) {
        this.inid = inid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.gid
     *
     * @return the value of inventory.gid
     * @mbg.generated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.gid
     *
     * @param gid the value for inventory.gid
     * @mbg.generated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.quantity
     *
     * @return the value of inventory.quantity
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.quantity
     *
     * @param quantity the value for inventory.quantity
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Inventory other = (Inventory) that;
        return (this.getInid() == null ? other.getInid() == null : this.getInid().equals(other.getInid()))
                && (this.getGid() == null ? other.getGid() == null : this.getGid().equals(other.getGid()))
                && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInid() == null) ? 0 : getInid().hashCode());
        result = prime * result + ((getGid() == null) ? 0 : getGid().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", inid=").append(inid);
        sb.append(", gid=").append(gid);
        sb.append(", quantity=").append(quantity);
        sb.append("]");
        return sb.toString();
    }
}