package com.aifule.jxc.core.domain;

public class Photos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.photoId
     *
     * @mbg.generated
     */
    private Integer photoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.gid
     *
     * @mbg.generated
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.photoname
     *
     * @mbg.generated
     */
    private String photoname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.photoId
     *
     * @return the value of photos.photoId
     * @mbg.generated
     */
    public Integer getPhotoid() {
        return photoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.photoId
     *
     * @param photoid the value for photos.photoId
     * @mbg.generated
     */
    public void setPhotoid(Integer photoid) {
        this.photoid = photoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.gid
     *
     * @return the value of photos.gid
     * @mbg.generated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.gid
     *
     * @param gid the value for photos.gid
     * @mbg.generated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.photoname
     *
     * @return the value of photos.photoname
     * @mbg.generated
     */
    public String getPhotoname() {
        return photoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.photoname
     *
     * @param photoname the value for photos.photoname
     * @mbg.generated
     */
    public void setPhotoname(String photoname) {
        this.photoname = photoname == null ? null : photoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Photos other = (Photos) that;
        return (this.getPhotoid() == null ? other.getPhotoid() == null : this.getPhotoid().equals(other.getPhotoid()))
                && (this.getGid() == null ? other.getGid() == null : this.getGid().equals(other.getGid()))
                && (this.getPhotoname() == null ? other.getPhotoname() == null : this.getPhotoname().equals(other.getPhotoname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPhotoid() == null) ? 0 : getPhotoid().hashCode());
        result = prime * result + ((getGid() == null) ? 0 : getGid().hashCode());
        result = prime * result + ((getPhotoname() == null) ? 0 : getPhotoname().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", photoid=").append(photoid);
        sb.append(", gid=").append(gid);
        sb.append(", photoname=").append(photoname);
        sb.append("]");
        return sb.toString();
    }
}