package com.aifule.jxc.core.dao.mysql;

import com.aifule.jxc.core.domain.Goodslei;
import com.aifule.jxc.core.mybatispage.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GoodsleiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodslei
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodslei
     *
     * @mbg.generated
     */
    int insert(Goodslei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodslei
     *
     * @mbg.generated
     */
    int insertSelective(Goodslei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodslei
     *
     * @mbg.generated
     */
    Goodslei selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodslei
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goodslei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodslei
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goodslei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Goodslei> selectsBySelective(@Param("record") Goodslei record, Page page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Goodslei> selectsByOneKey(@Param("name") String name, @Param("value") Object value, Page page);
}