package com.aifule.jxc.core.dao.mysql;

import com.aifule.jxc.core.domain.Goodsmiao;
import com.aifule.jxc.core.mybatispage.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GoodsmiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsmiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsmiao
     *
     * @mbg.generated
     */
    int insert(Goodsmiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsmiao
     *
     * @mbg.generated
     */
    int insertSelective(Goodsmiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsmiao
     *
     * @mbg.generated
     */
    Goodsmiao selectByPrimaryKey(Integer gaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsmiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goodsmiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsmiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goodsmiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Goodsmiao> selectsBySelective(@Param("record") Goodsmiao record, Page page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Goodsmiao> selectsByOneKey(@Param("name") String name, @Param("value") Object value, Page page);
}