package com.aifule.jxc.core.dao.mysql;

import com.aifule.jxc.core.domain.Inventory;
import com.aifule.jxc.core.mybatispage.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int insertSelective(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    Inventory selectByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Inventory> selectsBySelective(@Param("record") Inventory record, Page page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Inventory> selectsByOneKey(@Param("name") String name, @Param("value") Object value, Page page);
}