package com.aifule.jxc.core.dao.mysql;

import com.aifule.jxc.core.domain.Photos;
import com.aifule.jxc.core.mybatispage.Page;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer photoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    int insert(Photos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    int insertSelective(Photos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    Photos selectByPrimaryKey(Integer photoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Photos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Photos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Photos> selectsBySelective(@Param("record") Photos record, Page page);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment
     *
     * @mbg.generated
     */
    List<Photos> selectsByOneKey(@Param("name") String name, @Param("value") Object value, Page page);
}